/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.zim.actions;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.NoSuchElementException;
import net.sourceforge.jwbf.zim.actions.AllPageTitles;
import net.sourceforge.jwbf.zim.bots.ZimWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AllPageTitlesEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      File file0 = new File("", "");
      ZimWikiBot zimWikiBot0 = new ZimWikiBot(file0);
      AllPageTitles allPageTitles0 = new AllPageTitles(zimWikiBot0);
      // Undeclared exception!
      try {
        allPageTitles0.next();
        fail("Expecting exception: NoSuchElementException");
      } catch(NoSuchElementException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      File file0 = new File("", "");
      ZimWikiBot zimWikiBot0 = new ZimWikiBot(file0);
      AllPageTitles allPageTitles0 = new AllPageTitles(zimWikiBot0);
      Iterator<String> iterator0 = allPageTitles0.iterator();
      assertSame(allPageTitles0, iterator0);
  }

  @Test
  public void test2()  throws Throwable  {
      File file0 = new File("", "");
      ZimWikiBot zimWikiBot0 = new ZimWikiBot(file0);
      AllPageTitles allPageTitles0 = new AllPageTitles(zimWikiBot0);
      boolean boolean0 = allPageTitles0.hasNext();
      assertEquals(false, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("");
      File file0 = zimWikiBot0.getRootFolder();
      File file1 = new File(file0, "");
      ZimWikiBot zimWikiBot1 = new ZimWikiBot(file1);
      AllPageTitles allPageTitles0 = new AllPageTitles(zimWikiBot1);
      // Undeclared exception!
      try {
        allPageTitles0.remove();
        fail("Expecting exception: IllegalStateException");
      } catch(IllegalStateException e) {
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("");
      File file0 = zimWikiBot0.getRootFolder();
      File file1 = file0.getCanonicalFile();
      File file2 = file1.getParentFile();
      File file3 = new File(file2, "");
      ZimWikiBot zimWikiBot1 = new ZimWikiBot(file3);
      AllPageTitles allPageTitles0 = new AllPageTitles(zimWikiBot1);
      assertEquals("classes", allPageTitles0.next());
      assertEquals(true, allPageTitles0.hasNext());
      assertNotNull(allPageTitles0);
  }
}
