/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.editing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.MediaWiki;
import net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class GetRevisionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_10;
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision(mediaWiki_Version0, "!", 0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_10;
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision(mediaWiki_Version0, "!", 0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.DEVELOPMENT;
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision(mediaWiki_Version0, "g", 1786);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_10;
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision(mediaWiki_Version0, "D,{ka{pf~$)S!)Pf0H<", (-11));
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision
         */
      }
  }
}
