/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.editing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.TreeSet;
import net.sourceforge.jwbf.mediawiki.actions.editing.PostModifyContent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PostModifyContentEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LinkedHashSet<PostModifyContent> linkedHashSet0 = new LinkedHashSet<PostModifyContent>();
      boolean boolean0 = PostModifyContent.isIntersectionEmpty((Set<?>) null, (Set<?>) linkedHashSet0);
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      LinkedHashSet<PostModifyContent> linkedHashSet0 = new LinkedHashSet<PostModifyContent>();
      boolean boolean0 = PostModifyContent.isIntersectionEmpty((Set<?>) linkedHashSet0, (Set<?>) linkedHashSet0);
      assertEquals(true, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      LinkedHashSet<PostModifyContent> linkedHashSet0 = new LinkedHashSet<PostModifyContent>();
      boolean boolean0 = PostModifyContent.isIntersectionEmpty((Set<?>) linkedHashSet0, (Set<?>) null);
      assertEquals(true, boolean0);
  }

  @Test
  public void test3()  throws Throwable  {
      TreeSet<String> treeSet0 = new TreeSet<String>();
      treeSet0.add("use4i[fo");
      boolean boolean0 = PostModifyContent.isIntersectionEmpty((Set<?>) treeSet0, (Set<?>) treeSet0);
      assertEquals(false, boolean0);
  }
}
