/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.editing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import net.sourceforge.jwbf.mediawiki.actions.editing.PostModifyContent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestPostModifyContent {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        PostModifyContent.isIntersectionEmpty((Set<?>) null, (Set<?>) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.PostModifyContent
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      HashSet<String> hashSet0 = new HashSet<String>();
      // Undeclared exception!
      try {
        PostModifyContent.isIntersectionEmpty((Set<?>) hashSet0, (Set<?>) hashSet0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.PostModifyContent
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Locale locale0 = Locale.US;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      // Undeclared exception!
      try {
        PostModifyContent.isIntersectionEmpty(set0, (Set<?>) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.PostModifyContent
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      HashSet<String> hashSet0 = new HashSet<String>();
      hashSet0.add(" A");
      // Undeclared exception!
      try {
        PostModifyContent.isIntersectionEmpty((Set<?>) hashSet0, (Set<?>) hashSet0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.PostModifyContent
         */
      }
  }
}
