/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.editing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.Post;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.core.contentRep.Userinfo;
import net.sourceforge.jwbf.mediawiki.actions.MediaWiki;
import net.sourceforge.jwbf.mediawiki.actions.editing.GetApiToken;
import net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo;
import net.sourceforge.jwbf.mediawiki.actions.util.VersionException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestGetApiToken {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GetApiToken.Intoken getApiToken_Intoken0 = GetApiToken.Intoken.PROTECT;
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_12;
      GetUserinfo getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
      GetApiToken getApiToken0 = new GetApiToken(getApiToken_Intoken0, "PROTECT", mediaWiki_Version0, (Userinfo) getUserinfo0);
      getApiToken0.getToken();
  }

  @Test
  public void test1()  throws Throwable  {
      GetApiToken.Intoken getApiToken_Intoken0 = GetApiToken.Intoken.PROTECT;
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_12;
      GetUserinfo getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
      GetApiToken getApiToken0 = new GetApiToken(getApiToken_Intoken0, "PROTECT", mediaWiki_Version0, (Userinfo) getUserinfo0);
      assertNotNull(getApiToken0);
      
      boolean boolean0 = getApiToken0.hasMoreMessages();
      assertEquals(true, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      GetApiToken.Intoken getApiToken_Intoken0 = GetApiToken.Intoken.EMAIL;
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_14;
      GetUserinfo getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
      GetApiToken getApiToken0 = new GetApiToken(getApiToken_Intoken0, "unknown_action:fwsxSb?", mediaWiki_Version0, (Userinfo) getUserinfo0);
      assertNotNull(getApiToken0);
      
      Post post0 = new Post("unknown_action:fwsxSb?", "unknown_action:fwsxSb?");
      String string0 = getApiToken0.processReturningText("unknown_action:fwsxSb?", (HttpAction) post0);
      assertNotNull(string0);
      assertEquals(true, getApiToken0.hasMoreMessages());
  }

  @Test
  public void test3()  throws Throwable  {
      GetApiToken.Intoken getApiToken_Intoken0 = GetApiToken.Intoken.EMAIL;
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_14;
      GetUserinfo getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
      GetApiToken getApiToken0 = new GetApiToken(getApiToken_Intoken0, "unknown_action:fwsxSb?", mediaWiki_Version0, (Userinfo) getUserinfo0);
      assertNotNull(getApiToken0);
      
      Get get0 = (Get)getApiToken0.getNextMessage();
      String string0 = getApiToken0.processReturningText("unknown_action:fwsxSb?", (HttpAction) get0);
      assertNotNull(string0);
      assertEquals(false, getApiToken0.hasMoreMessages());
  }

  @Test
  public void test4()  throws Throwable  {
      GetApiToken.Intoken getApiToken_Intoken0 = GetApiToken.Intoken.PROTECT;
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_12;
      GetUserinfo getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
      GetApiToken getApiToken0 = new GetApiToken(getApiToken_Intoken0, "PROTECT", mediaWiki_Version0, (Userinfo) getUserinfo0);
      assertNotNull(getApiToken0);
      
      Get get0 = (Get)getApiToken0.getNextMessage();
      String string0 = getApiToken0.processReturningText("PROTECT", (HttpAction) get0);
      assertNotNull(string0);
      assertEquals(false, getApiToken0.hasMoreMessages());
      assertEquals("/api.php?action=query&prop=info&intoken=protect&titles=PROTECT&format=xml", get0.getRequest());
  }

  @Test
  public void test5()  throws Throwable  {
      GetApiToken.Intoken getApiToken_Intoken0 = GetApiToken.Intoken.PROTECT;
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_12;
      GetUserinfo getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
      GetApiToken getApiToken0 = new GetApiToken(getApiToken_Intoken0, "PROTECT", mediaWiki_Version0, (Userinfo) getUserinfo0);
      assertNotNull(getApiToken0);
      
      Get get0 = (Get)getApiToken0.getNextMessage();
      assertNotNull(get0);
      
      getApiToken0.getNextMessage();
      assertEquals(false, getApiToken0.hasMoreMessages());
  }
}
