/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.bots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import net.sourceforge.jwbf.core.actions.HttpActionClient;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestMediaWikiBot {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot("http://www.slf4j.org/codes.html#substituteLogger.php");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      File file0 = new File("$@.@ 5%*", "$@.@ 5%*");
      URI uRI0 = file0.toURI();
      URL uRL0 = uRI0.toURL();
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot(uRL0, false);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot("http://www.slf4j.org/codes.html#substituteLogger/");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot((URL) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot((HttpActionClient) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot("http://www.slf4j.org/codes.html#substituteLogger/");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot("http:/w#wYslf4j.4rg/cdes.BtFl#substituteLogge`");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test12()  throws Throwable  {
      File file0 = new File("_O,9UxnN86Wn|x");
      URI uRI0 = file0.toURI();
      URL uRL0 = uRI0.toURL();
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot(uRL0, true);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }

  @Test
  public void test14()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = null;
      try {
        mediaWikiBot0 = new MediaWikiBot("http://www.slf4j.org/codes.html#substituteLogger/");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot
         */
      }
  }
}
