/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.core.contentRep;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.io.File;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.bots.WikiBot;
import net.sourceforge.jwbf.core.contentRep.Article;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import net.sourceforge.jwbf.zim.bots.ZimWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestArticle {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pP");
      Article article0 = new Article((WikiBot) zimWikiBot0, "pP");
      article0.save("pP");
      article0.addText("pP");
      assertEquals("pP", article0.getText());
      assertEquals("pP", article0.getEditSummary());
  }

  @Test
  public void test1()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pP");
      Article article0 = new Article((WikiBot) zimWikiBot0, "pP");
      article0.delete();
      assertEquals("", article0.getText());
  }

  @Test
  public void test2()  throws Throwable  {
      File file0 = new File("q", "q");
      ZimWikiBot zimWikiBot0 = new ZimWikiBot(file0);
      Article article0 = new Article((WikiBot) zimWikiBot0, "q");
      // Undeclared exception!
      try {
        article0.addTextnl("q");
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: q/q/q.txt (No such file or directory)
         */
      }
      assertEquals("\nq", article0.getText());
  }

  @Test
  public void test3()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = new MediaWikiBot();
      Article article0 = new Article((WikiBot) mediaWikiBot0, ">_)Z&+IL<?o%");
      // Undeclared exception!
      try {
        article0.clear();
        fail("Expecting exception: ActionException");
      } catch(ActionException e) {
        /*
         * Please login first
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      File file0 = new File("q", "q");
      ZimWikiBot zimWikiBot0 = new ZimWikiBot(file0);
      Article article0 = new Article((WikiBot) zimWikiBot0, "q");
      boolean boolean0 = article0.isRedirect();
      assertEquals(false, boolean0);
  }

  @Test
  public void test5()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("FtI");
      Article article0 = new Article((WikiBot) zimWikiBot0, "FtI");
      article0.setEditor("FtI");
      String string0 = article0.getEditor();
      assertNotNull(string0);
      assertEquals("FtI", article0.getEditor());
      assertEquals("FtI", string0);
  }

  @Test
  public void test6()  throws Throwable  {
      File file0 = new File("q", "q");
      ZimWikiBot zimWikiBot0 = new ZimWikiBot(file0);
      Article article0 = new Article((WikiBot) zimWikiBot0, "q");
      String string0 = article0.getTitle();
      assertEquals("q", string0);
  }

  @Test
  public void test7()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pP");
      Article article0 = new Article((WikiBot) zimWikiBot0, "pP");
      article0.setMinorEdit(true);
      assertEquals(true, article0.isMinorEdit());
  }

  @Test
  public void test8()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pP");
      Article article0 = new Article((WikiBot) zimWikiBot0, "pP");
      article0.setTitle("pP");
      assertEquals("pP", article0.getTitle());
  }

  @Test
  public void test9()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pP");
      Article article0 = new Article((WikiBot) zimWikiBot0, "pP");
      SimpleArticle simpleArticle0 = article0.getSimpleArticle();
      assertEquals("", simpleArticle0.getRevisionId());
  }

  @Test
  public void test10()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = new MediaWikiBot();
      SimpleArticle simpleArticle0 = new SimpleArticle();
      Article article0 = new Article((WikiBot) mediaWikiBot0, simpleArticle0);
      // Undeclared exception!
      String string0 = "";
      try {
        string0 = article0.getEditor();
        fail("Expecting exception: IllegalStateException");
      } catch(IllegalStateException e) {
        /*
         * please use another constructor or inject net.sourceforge.jwbf.core.bots.HttpBot
         */
      }
  }

  @Test
  public void test11()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pP");
      Article article0 = new Article((WikiBot) zimWikiBot0, "pP");
      // Undeclared exception!
      try {
        article0.addText("pP");
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: pP/pP.txt (No such file or directory)
         */
      }
      assertEquals("pP", article0.getText());
  }

  @Test
  public void test12()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("d@.?ht%l)1:X,+C");
      Article article0 = new Article((WikiBot) zimWikiBot0, "d@.?ht%l)1:X,+C");
      // Undeclared exception!
      String string0 = "";
      try {
        string0 = article0.getRevisionId();
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: d@.?ht%l)1:X,+C/d@.?ht%l)1:X,+C.txt (No such file or directory)
         */
      }
  }

  @Test
  public void test13()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pP");
      Article article0 = new Article((WikiBot) zimWikiBot0, "pP");
      article0.save("pP");
      String string0 = article0.getEditSummary();
      assertNotNull(string0);
      assertEquals("pP", article0.getEditSummary());
      assertEquals("pP", string0);
  }

  @Test
  public void test14()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("FtI");
      Article article0 = new Article((WikiBot) zimWikiBot0, "FtI");
      // Undeclared exception!
      String string0 = "";
      try {
        string0 = article0.getEditSummary();
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: FtI/FtI.txt (No such file or directory)
         */
      }
  }

  @Test
  public void test15()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = new MediaWikiBot();
      SimpleArticle simpleArticle0 = new SimpleArticle();
      Article article0 = new Article((WikiBot) mediaWikiBot0, simpleArticle0);
      // Undeclared exception!
      boolean boolean0 = false;
      try {
        boolean0 = article0.isMinorEdit();
        fail("Expecting exception: IllegalStateException");
      } catch(IllegalStateException e) {
        /*
         * please use another constructor or inject net.sourceforge.jwbf.core.bots.HttpBot
         */
      }
  }

  @Test
  public void test16()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("$V-0z3mF");
      Article article0 = new Article((WikiBot) zimWikiBot0, "$V-0z3mF");
      // Undeclared exception!
      try {
        article0.getEditTimestamp();
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: $V-0z3mF/$V-0z3mF.txt (No such file or directory)
         */
      }
  }
}
