/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.zim.bots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.core.bots.util.CacheHandler;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import net.sourceforge.jwbf.core.contentRep.Userinfo;
import net.sourceforge.jwbf.zim.bots.ZimWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestZimWikiBot {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("Nihds'ul<");
      Userinfo userinfo0 = zimWikiBot0.getUserinfo();
      assertEquals("ac1gf", userinfo0.getUsername());
  }

  @Test
  public void test1()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("Nihds'ul<");
      String string0 = zimWikiBot0.getWikiType();
      assertEquals("Zim", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("r");
      // Undeclared exception!
      try {
        zimWikiBot0.readData("r");
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: r/r.txt (No such file or directory)
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("Nihds'ul<");
      // Undeclared exception!
      try {
        zimWikiBot0.getArticle("Zim");
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: Nihds'ul</Zim.txt (No such file or directory)
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("r");
      zimWikiBot0.writeContent((SimpleArticle) null);
      assertEquals(false, zimWikiBot0.hasCacheHandler());
  }

  @Test
  public void test5()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("57U,S+j#o8';(i.>");
      zimWikiBot0.delete("57U,S+j#o8';(i.>");
      assertEquals(false, zimWikiBot0.hasCacheHandler());
  }

  @Test
  public void test6()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("Nihds'ul<");
      zimWikiBot0.setCacheHandler((CacheHandler) null);
      assertEquals("Zim", zimWikiBot0.getWikiType());
  }

  @Test
  public void test7()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("57U,S+j#o8';(i.>");
      try {
        zimWikiBot0.login("57U,S+j#o8';(i.>", "57U,S+j#o8';(i.>");
        fail("Expecting exception: ActionException");
      } catch(ActionException e) {
        /*
         * login is not supported because this is a desktopwiki
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("57U,S+j#o8';(i.>");
      boolean boolean0 = zimWikiBot0.hasCacheHandler();
      assertEquals(false, boolean0);
  }
}
