/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.zim.bots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.core.bots.util.CacheHandler;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import net.sourceforge.jwbf.core.contentRep.Userinfo;
import net.sourceforge.jwbf.zim.bots.ZimWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ZimWikiBotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("d");
      Userinfo userinfo0 = zimWikiBot0.getUserinfo();
      assertEquals("ac1gf", userinfo0.getUsername());
  }

  @Test
  public void test1()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("d");
      String string0 = zimWikiBot0.getWikiType();
      assertEquals("Zim", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("d");
      // Undeclared exception!
      try {
        zimWikiBot0.readData("d");
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: d/d.txt (No such file or directory)
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("pu\"qS");
      // Undeclared exception!
      try {
        zimWikiBot0.getArticle("pu\"qS");
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * java.io.FileNotFoundException: pu\"qS/pu\"qS.txt (No such file or directory)
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("d");
      SimpleArticle simpleArticle0 = new SimpleArticle();
      zimWikiBot0.writeContent(simpleArticle0);
      assertEquals("", simpleArticle0.getLabel());
  }

  @Test
  public void test5()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("d");
      zimWikiBot0.delete("d");
      assertEquals("Zim", zimWikiBot0.getWikiType());
  }

  @Test
  public void test6()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("?x:");
      zimWikiBot0.setCacheHandler((CacheHandler) null);
      assertEquals("Zim", zimWikiBot0.getWikiType());
  }

  @Test
  public void test7()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("?x:");
      try {
        zimWikiBot0.login("?x:", "?x:");
        fail("Expecting exception: ActionException");
      } catch(ActionException e) {
        /*
         * login is not supported because this is a desktopwiki
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      ZimWikiBot zimWikiBot0 = new ZimWikiBot("d");
      boolean boolean0 = zimWikiBot0.hasCacheHandler();
      assertEquals(false, boolean0);
  }
}
