/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.core.actions;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Map;
import net.sourceforge.jwbf.core.actions.Post;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PostEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Post post0 = new Post("}d=4z[cje");
      String string0 = post0.getCharset();
      assertNotNull(string0);
      assertEquals("}d=4z[cje", post0.getRequest());
      assertEquals("utf-8", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      Post post0 = new Post("}d=4z[cje");
      String string0 = post0.getRequest();
      assertEquals("utf-8", post0.getCharset());
      assertNotNull(string0);
      assertEquals("}d=4z[cje", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      Post post0 = new Post("}d=4z[cje");
      Map<String, Object> map0 = post0.getParams();
      assertEquals("}d=4z[cje", post0.getRequest());
      assertEquals("utf-8", post0.getCharset());
      assertNotNull(map0);
  }

  @Test
  public void test3()  throws Throwable  {
      Post post0 = new Post("}d=4z[cje");
      post0.addParam("}d=4z[cje", "}d=4z[cje");
      assertEquals("utf-8", post0.getCharset());
      assertEquals("}d=4z[cje", post0.getRequest());
  }
}
