/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.core.bots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.net.URL;
import net.sourceforge.jwbf.core.actions.ContentProcessable;
import net.sourceforge.jwbf.core.actions.GetPage;
import net.sourceforge.jwbf.core.actions.HttpActionClient;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.bots.HttpBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class HttpBotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HttpBot httpBot0 = null;
      try {
        httpBot0 = new HttpBot((URL) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      HttpBot httpBot0 = new HttpBot();
      // Undeclared exception!
      try {
        httpBot0.setConnection("");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * java.net.MalformedURLException: no protocol: 
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      HttpBot httpBot0 = new HttpBot((HttpActionClient) null);
      // Undeclared exception!
      try {
        httpBot0.setConnection((HttpActionClient) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      HttpBot httpBot0 = null;
      try {
        httpBot0 = new HttpBot("/-ZB(|vz%vk");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * java.net.MalformedURLException: no protocol: /-ZB(|vz%vk
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      HttpBot httpBot0 = new HttpBot();
      GetPage getPage0 = new GetPage("");
      // Undeclared exception!
      try {
        httpBot0.performAction((ContentProcessable) getPage0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test5()  throws Throwable  {
      HttpBot httpBot0 = new HttpBot();
      // Undeclared exception!
      try {
        httpBot0.getPage("(BC6AmQcLYRVFz&");
        fail("Expecting exception: ActionException");
      } catch(ActionException e) {
        /*
         * java.net.MalformedURLException: no protocol: (BC6AmQcLYRVFz&
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      HttpBot httpBot0 = new HttpBot();
      // Undeclared exception!
      try {
        httpBot0.getHostUrl();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test7()  throws Throwable  {
      HttpBot httpBot0 = new HttpBot();
      // Undeclared exception!
      try {
        httpBot0.getBytes("");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test8()  throws Throwable  {
      HttpBot httpBot0 = new HttpBot();
      HttpActionClient httpActionClient0 = httpBot0.getClient();
      assertNull(httpActionClient0);
  }
}
