/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.queries;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.queries.CategoryMembersSimple;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CategoryMembersSimpleEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MediaWikiBot mediaWikiBot0 = new MediaWikiBot();
      CategoryMembersSimple categoryMembersSimple0 = null;
      try {
        categoryMembersSimple0 = new CategoryMembersSimple(mediaWikiBot0, "Yp");
        fail("Expecting exception: IllegalStateException");
      } catch(IllegalStateException e) {
        /*
         * please use another constructor or inject net.sourceforge.jwbf.core.bots.HttpBot
         */
      }
  }
}
