/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.contentRep;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.mediawiki.contentRep.CategoryItem;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class CategoryItemEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      CategoryItem categoryItem0 = new CategoryItem();
      String string0 = categoryItem0.getTitle();
      assertEquals("", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      CategoryItem categoryItem0 = new CategoryItem();
      int int0 = categoryItem0.getPageid();
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      CategoryItem categoryItem0 = new CategoryItem();
      categoryItem0.setTitle("");
      assertEquals(0, categoryItem0.getNamespace());
  }

  @Test
  public void test3()  throws Throwable  {
      CategoryItem categoryItem0 = new CategoryItem();
      int int0 = categoryItem0.getNamespace();
      assertEquals(0, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      CategoryItem categoryItem0 = new CategoryItem();
      categoryItem0.setPageid(0);
      assertEquals(0, categoryItem0.getPageid());
  }

  @Test
  public void test5()  throws Throwable  {
      CategoryItem categoryItem0 = new CategoryItem();
      categoryItem0.setNamespace(0);
      assertEquals(0, categoryItem0.getNamespace());
  }

  @Test
  public void test6()  throws Throwable  {
      CategoryItem categoryItem0 = new CategoryItem();
      String string0 = categoryItem0.toString();
      assertEquals("", string0);
  }
}
