/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.contentRep;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.Map;
import net.sourceforge.jwbf.mediawiki.contentRep.LoginData;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class LoginDataEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      String string0 = loginData0.getUserName();
      assertEquals(false, loginData0.isLoggedIn());
      assertNotNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      boolean boolean0 = loginData0.isLoggedIn();
      assertEquals(false, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      loginData0.setup("P,g<Y+1g+7Ey2)WZ", false);
      assertEquals("P,g<Y+1g+7Ey2)WZ", loginData0.getUserName());
  }

  @Test
  public void test3()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      loginData0.setup("I+ ZK1^{>", false, (Map<String, String>) hashMap0);
      assertEquals(false, loginData0.isLoggedIn());
  }
}
