/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.contentRep;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.mediawiki.contentRep.LogItem;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestLogItem {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LogItem logItem0 = new LogItem();
      String string0 = logItem0.toString();
      assertNotNull(string0);
      assertEquals("* null was null by null", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      LogItem logItem0 = new LogItem();
      logItem0.setTitle("");
      assertEquals("", logItem0.getTitle());
  }

  @Test
  public void test2()  throws Throwable  {
      LogItem logItem0 = new LogItem();
      logItem0.setUser("");
      assertEquals("", logItem0.getUser());
  }

  @Test
  public void test3()  throws Throwable  {
      LogItem logItem0 = new LogItem();
      logItem0.setType("oV!J)(q?&D~-~q");
      assertNull(logItem0.getTitle());
  }
}
