/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.mediawiki.actions.HTMLEntities;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestHTMLEntities {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      String string0 = HTMLEntities.unhtmlQuotes("&FQiJ9AT;");
      assertNotNull(string0);
      assertEquals("&FQiJ9AT;", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      String string0 = HTMLEntities.unhtmlentities("&FQiJ9AT;");
      assertEquals("&FQiJ9AT;", string0);
      assertNotNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      String string0 = HTMLEntities.unhtmlentities("~&!$#AL:;#'^; oV&");
      assertEquals("~&!$#AL:;#'^; oV&", string0);
      assertNotNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try {
        HTMLEntities.unhtmlentities("&#m;ECcMh&");
        fail("Expecting exception: NumberFormatException");
      } catch(NumberFormatException e) {
        /*
         * For input string: \"m\"
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      String string0 = HTMLEntities.unhtmlentities("&hArr;");
      assertEquals("\u21D4", string0);
      assertNotNull(string0);
  }
}
