/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.trac.actions;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.Post;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.trac.actions.GetRevision;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestGetRevision {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("a3jZiuUqhp4>T");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("a3jZiuUqhp4>T");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("a3jZiuUqhp4>T");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("cF-[0euxp");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("cF-[0euxp");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("hiliTg1Nt");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("a3jZiuUqhp4>T");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("cF-[0euxp");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test9()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("cF-[0euxp");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }

  @Test
  public void test10()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("hiliTg1Nt");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.trac.actions.GetRevision
         */
      }
  }
}
