/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.trac.bots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.net.MalformedURLException;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.trac.bots.TracWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TracWikiBotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      TracWikiBot tracWikiBot0 = new TracWikiBot("http:o?_n7dumWa{jd");
      try {
        tracWikiBot0.readContent("http:o?_n7dumWa{jd");
        fail("Expecting exception: ActionException");
      } catch(ActionException e) {
        /*
         * java.lang.IllegalArgumentException
         */
      }
  }
}
