/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.inyoka.actions;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.Post;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.inyoka.actions.GetRevision;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestGetRevision {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("26jB");
      getRevision0.getArticle();
  }

  @Test
  public void test1()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("26jB");
      assertNotNull(getRevision0);
      
      boolean boolean0 = getRevision0.isSelfExecuter();
      assertEquals(false, boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision("");
        fail("Expecting exception: ProcessException");
      } catch(ProcessException e) {
        /*
         * articlename is empty
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("(-f'?EgT");
      assertNotNull(getRevision0);
      
      Get get0 = (Get)getRevision0.getNextMessage();
      assertNotNull(get0);
      assertEquals("utf-8/(-f'?EgT?action=export&format=raw&", get0.toString());
      
      Get get1 = (Get)getRevision0.getNextMessage();
      String string0 = getRevision0.processReturningText("(-f'?EgT", (HttpAction) get1);
      assertEquals(true, getRevision0.hasMoreMessages());
      assertEquals("utf-8/(-f'?EgT", get1.toString());
      assertNotNull(string0);
      assertFalse(get1.equals(get0));
  }

  @Test
  public void test4()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("26jB");
      assertNotNull(getRevision0);
      
      Get get0 = (Get)getRevision0.getNextMessage();
      String string0 = getRevision0.processReturningText("26jB", (HttpAction) get0);
      assertEquals("utf-8/26jB?action=export&format=raw&", get0.toString());
      assertNotNull(string0);
  }

  @Test
  public void test5()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("(-f'?EgT");
      assertNotNull(getRevision0);
      
      getRevision0.getNextMessage();
      getRevision0.getNextMessage();
      Get get0 = (Get)getRevision0.getNextMessage();
      // Undeclared exception!
      try {
        getRevision0.processReturningText("(-f'?EgT", (HttpAction) get0);
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * no date found
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("26jB");
      Post post0 = new Post("", "26jB");
      String string0 = getRevision0.processReturningText("", (HttpAction) post0);
      assertEquals("", string0);
  }

  @Test
  public void test7()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("26jB");
      assertNotNull(getRevision0);
      
      boolean boolean0 = getRevision0.hasMoreMessages();
      assertEquals(true, boolean0);
  }

  @Test
  public void test8()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("(-f'?EgT");
      assertNotNull(getRevision0);
      
      Get get0 = (Get)getRevision0.getNextMessage();
      assertEquals("utf-8/(-f'?EgT?action=export&format=raw&", get0.toString());
      assertNotNull(get0);
      
      boolean boolean0 = getRevision0.hasMoreMessages();
      assertEquals(true, boolean0);
  }

  @Test
  public void test9()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("(-f'?EgT");
      assertNotNull(getRevision0);
      
      Get get0 = (Get)getRevision0.getNextMessage();
      assertNotNull(get0);
      assertEquals("utf-8/(-f'?EgT?action=export&format=raw&", get0.toString());
      
      Get get1 = (Get)getRevision0.getNextMessage();
      assertEquals("utf-8/(-f'?EgT", get1.toString());
      assertNotNull(get1);
      
      boolean boolean0 = getRevision0.hasMoreMessages();
      assertEquals(true, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      GetRevision getRevision0 = new GetRevision("(-f'?EgT");
      assertNotNull(getRevision0);
      
      getRevision0.getNextMessage();
      getRevision0.getNextMessage();
      getRevision0.getNextMessage();
      boolean boolean0 = getRevision0.hasMoreMessages();
      assertEquals(false, getRevision0.hasMoreMessages());
      assertEquals(false, boolean0);
  }
}
