/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.login;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.Post;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.login.PostLogin;
import net.sourceforge.jwbf.mediawiki.contentRep.LoginData;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PostLoginEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLogin postLogin0 = new PostLogin("", "", "", loginData0);
      Post post0 = (Post)postLogin0.getNextMessage();
      assertNotNull(post0);
      assertEquals("/api.php?action=login&format=xml", post0.getRequest());
  }

  @Test
  public void test1()  throws Throwable  {
      PostLogin postLogin0 = new PostLogin((String) null, (String) null, (String) null, (LoginData) null);
      try {
        postLogin0.processAllReturningText((String) null);
        fail("Expecting exception: ProcessException");
      } catch(ProcessException e) {
        /*
         * No regular content was found, check your api
         * ::null
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLogin postLogin0 = new PostLogin("", "", "", loginData0);
      postLogin0.hasMoreMessages();
      boolean boolean0 = postLogin0.hasMoreMessages();
      assertEquals(false, postLogin0.hasMoreMessages());
      assertEquals(false, boolean0);
  }
}
