/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.login;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.Map;
import net.sourceforge.jwbf.core.actions.Post;
import net.sourceforge.jwbf.core.actions.util.CookieException;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.mediawiki.actions.login.PostLoginOld;
import net.sourceforge.jwbf.mediawiki.contentRep.LoginData;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PostLoginOldEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLoginOld postLoginOld0 = new PostLoginOld("", "", "", loginData0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>(1);
      Post post0 = (Post)postLoginOld0.getNextMessage();
      assertNotNull(post0);
      
      try {
        postLoginOld0.validateReturningCookies((Map<String, String>) hashMap0, (HttpAction) post0);
        fail("Expecting exception: CookieException");
      } catch(CookieException e) {
        /*
         * No cookies found.
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLoginOld postLoginOld0 = new PostLoginOld("49Y;aYBnd[s^~@?5rL", "49Y;aYBnd[s^~@?5rL", "49Y;aYBnd[s^~@?5rL", loginData0);
      try {
        postLoginOld0.validateAllReturningCookies((Map<String, String>) null);
        fail("Expecting exception: CookieException");
      } catch(CookieException e) {
        /*
         * Cookiearray is null.
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLoginOld postLoginOld0 = new PostLoginOld("", "", "", loginData0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>(1);
      hashMap0.put("", "");
      postLoginOld0.validateAllReturningCookies((Map<String, String>) hashMap0);
      assertEquals(true, loginData0.isLoggedIn());
  }

  @Test
  public void test3()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLoginOld postLoginOld0 = new PostLoginOld("4{e1*<5qb}R(w`", "4{e1*<5qb}R(w`", "4{e1*<5qb}R(w`", loginData0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>(39992);
      hashMap0.put("4{e1*<5qb}R(w`", "4{e1*<5qb}R(w`");
      try {
        postLoginOld0.validateAllReturningCookies((Map<String, String>) hashMap0);
        fail("Expecting exception: CookieException");
      } catch(CookieException e) {
        /*
         * Login failed: Check Username and Password.
         */
      }
  }
}
