/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.login;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.login.PostLogin;
import net.sourceforge.jwbf.mediawiki.contentRep.LoginData;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestPostLogin {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLogin postLogin0 = null;
      try {
        postLogin0 = new PostLogin("I]X<9Vx0", "I]X<9Vx0", "I]X<9Vx0", loginData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.login.PostLogin
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLogin postLogin0 = null;
      try {
        postLogin0 = new PostLogin("I]X<9Vx0", "I]X<9Vx0", "I]X<9Vx0", loginData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.login.PostLogin
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLogin postLogin0 = null;
      try {
        postLogin0 = new PostLogin((String) null, (String) null, (String) null, loginData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.login.PostLogin
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLogin postLogin0 = null;
      try {
        postLogin0 = new PostLogin("I]X<9Vx0", "I]X<9Vx0", "I]X<9Vx0", loginData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.login.PostLogin
         */
      }
  }
}
