/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.util.Map;
import net.sourceforge.jwbf.JWBF;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class JWBFEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Class<?> class0 = JWBF.class;
      String string0 = JWBF.getVersion(class0);
      assertEquals("Version Unknown", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      Class<?> class0 = JWBF.class;
      String string0 = JWBF.getPartId(class0);
      assertNotNull(string0);
      assertEquals("No Module for net.sourceforge.jwbf.JWBF", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      Map<String, String> map0 = JWBF.getVersion();
      assertEquals(5, map0.size());
  }

  @Test
  public void test3()  throws Throwable  {
      JWBF.printVersion();
  }
}
