/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import ch.qos.logback.core.joran.spi.ConsoleTarget;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.MediaWiki;
import net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision;
import net.sourceforge.jwbf.mediawiki.actions.login.PostLoginOld;
import net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo;
import net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion;
import net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo;
import net.sourceforge.jwbf.mediawiki.actions.util.MWAction;
import net.sourceforge.jwbf.mediawiki.actions.util.VersionException;
import net.sourceforge.jwbf.mediawiki.contentRep.LoginData;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestMWAction {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      LoginData loginData0 = new LoginData();
      PostLoginOld postLoginOld0 = null;
      try {
        postLoginOld0 = new PostLoginOld("-986-746|1175e72|1510|1219|5]0|0|408||", "-986-746|1175e72|1510|1219|5]0|0|408||", "-986-746|1175e72|1510|1219|5]0|0|408||", loginData0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.login.PostLoginOld
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_15;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_15;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.UNKNOWN;
      GetRevision getRevision0 = null;
      try {
        getRevision0 = new GetRevision(mediaWiki_Version0, "0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0", 0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.editing.GetRevision
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Class<?> class0 = ConsoleTarget.class;
      // Undeclared exception!
      try {
        MWAction.findSupportedVersions(class0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.util.MWAction
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_17;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try {
        MWAction.createNsString((int[]) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.util.MWAction
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      int[] intArray0 = new int[21];
      // Undeclared exception!
      try {
        MWAction.createNsString(intArray0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.util.MWAction
         */
      }
  }

  @Test
  public void test8()  throws Throwable  {
      Siteinfo siteinfo0 = null;
      try {
        siteinfo0 = new Siteinfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo
         */
      }
  }
}
