/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.inyoka.bots;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.net.MalformedURLException;
import java.util.Map;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.core.contentRep.SimpleArticle;
import net.sourceforge.jwbf.core.contentRep.Userinfo;
import net.sourceforge.jwbf.inyoka.bots.InyokaWikiBot;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class InyokaWikiBotEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      InyokaWikiBot inyokaWikiBot0 = new InyokaWikiBot("http:/lww.}lfjogqodes.0l#su\ttui.tgge");
      Userinfo userinfo0 = inyokaWikiBot0.getUserinfo();
      assertEquals("unknown", userinfo0.getUsername());
  }

  @Test
  public void test1()  throws Throwable  {
      InyokaWikiBot inyokaWikiBot0 = new InyokaWikiBot("http:/lww.}lfjogqodes.0l#su\ttui.tgge");
      try {
        inyokaWikiBot0.getArticle("http:/lww.}lfjogqodes.0l#su\ttui.tgge");
        fail("Expecting exception: ActionException");
      } catch(ActionException e) {
        /*
         * java.lang.IllegalArgumentException
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      InyokaWikiBot inyokaWikiBot0 = new InyokaWikiBot("http:/lww.}lfjogqodes.0l#su\ttui.tgge");
      inyokaWikiBot0.setCacheHandler((Map<String, SimpleArticle>) null);
      assertEquals("http:/lww.}lfjogqodes.0l#su\ttui.tgge", inyokaWikiBot0.getUrl());
  }

  @Test
  public void test3()  throws Throwable  {
      InyokaWikiBot inyokaWikiBot0 = new InyokaWikiBot("http:/lww.}lfjogqodes.0l#su\ttui.tgge");
      String string0 = inyokaWikiBot0.getWikiType();
      assertNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      InyokaWikiBot inyokaWikiBot0 = new InyokaWikiBot("http:/lww.}lfjogqodes.0l#su\ttui.tgge");
      boolean boolean0 = inyokaWikiBot0.hasCacheHandler();
      assertEquals(false, boolean0);
  }
}
