/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.meta;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.Get;
import net.sourceforge.jwbf.core.actions.util.ActionException;
import net.sourceforge.jwbf.core.actions.util.HttpAction;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion;
import net.sourceforge.jwbf.mediawiki.bots.MediaWikiBot;
import org.jdom.Content;
import org.jdom.Element;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestGetVersion {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion((MediaWikiBot) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      GetVersion getVersion0 = null;
      try {
        getVersion0 = new GetVersion();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetVersion
         */
      }
  }
}
