/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.meta;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo;
import org.jdom.Content;
import org.jdom.Element;
import org.jdom.Namespace;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestSiteinfo {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Siteinfo siteinfo0 = null;
      try {
        siteinfo0 = new Siteinfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Siteinfo siteinfo0 = null;
      try {
        siteinfo0 = new Siteinfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      Siteinfo siteinfo0 = null;
      try {
        siteinfo0 = new Siteinfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Siteinfo siteinfo0 = null;
      try {
        siteinfo0 = new Siteinfo();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.Siteinfo
         */
      }
  }
}
