/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.jwbf.mediawiki.actions.meta;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sourceforge.jwbf.core.actions.util.ProcessException;
import net.sourceforge.jwbf.mediawiki.actions.MediaWiki;
import net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo;
import net.sourceforge.jwbf.mediawiki.actions.util.VersionException;
import org.jdom.Content;
import org.jdom.Element;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestGetUserinfo {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_13;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test1()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_11;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test2()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_13;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test3()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_11;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test4()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_15;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test5()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_11;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test6()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_13;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }

  @Test
  public void test7()  throws Throwable  {
      MediaWiki.Version mediaWiki_Version0 = MediaWiki.Version.MW1_11;
      GetUserinfo getUserinfo0 = null;
      try {
        getUserinfo0 = new GetUserinfo(mediaWiki_Version0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class net.sourceforge.jwbf.mediawiki.actions.meta.GetUserinfo
         */
      }
  }
}
